### ISSUE TITLE
Install of title 00000000-00000000  failed.

### ISSUE THREAD

**Issue by MisterAlexEsquire** [crediar/wupinstaller#1]
WUP Installer appears to be sometimes reading title ID numbers as all Zeroes. Not sure the cause.

Can you clarify what causes the program to throw an **MCP_InstallGetInfo** error?

![img_20161204_193405](https://cloud.githubusercontent.com/assets/19982802/20872060/2f011cb4-ba61-11e6-8d45-fbd3fd258b24.jpg)

**Comment by crediar** [comment]
First of all that version is not by me, please ask Yardape8000 for any issues.
Also this isn't support forum but about issues with the application.
